# Generated by Django 5.2.8 on 2025-12-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
            ],
            options={
                'verbose_name': 'WaitlistEntry',
                'verbose_name_plural': 'WaitlistEntrys',
            },
        ),
    ]
